[package]
name = "slm"
version = "0.2.0"
edition = "2021"

[dependencies]
sysinfo="0.32.0"
chrono = "0.4.38"
crossterm = "0.28.1"
ratatui = "0.29.0"
csv = "1.3.1"
clap= { version = "4.5.22", features = ["derive"] }
